name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Java code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkout Docker scripts
        uses: actions/checkout@v3
        with:
          repository: czyzewskijakub/practice-software-testing
          ref: main

      - name: Run scripts
        run: |
          docker-compose up -d
          docker-compose exec -T laravel-api php artisan migrate:fresh --seed --force
          docker-compose exec -T laravel-api php artisan queue:work

      - name: Build with Maven
        run: mvn -B test --file pom.xml
