name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkout Docker repository
        run: |
          git clone https://github.com/czyzewskijakub/practice-software-testing.git docker-repo
          cd docker-repo

      - name: Start Docker containers
        run: |
          docker-compose up -d
          docker-compose exec laravel-api php artisan migrate:fresh --seed --force
          docker-compose exec laravel-api php artisan queue:work

      - name: Build with Maven
        run: mvn -B test --file ../path/to/your/code/pom.xml

      - name: Stop Docker containers
        run: |
          cd ../path/to/docker-repo
          docker-compose down
